language: node_js
node_js:
  - "6"
  - "4.4"
  - "iojs"
cache:
  directories:
    - node_modules
    - bower_componets
after_success:
- ./node_modules/.bin/jscover models models-cov
- UCBACM_COV=1 ./node_modules/.bin/mocha tests/ -R mocha-lcov-reporter | ./node_modules/.bin/coveralls
