language: node_js
node_js:
  - "6"
  - "4.4"
  - "iojs"
cache:
  directories:
    - node_modules
    - bower_componets
services:
  - postgresql
before_script:
  - psql -c 'create database ucbacm;' -U postgres
after_script:
- npm run migrate
- node_modules/.bin/istanbul cover node_modules/mocha/bin/_mocha --report lcovonly tests/
- npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls
